## Tensors

In [1]:
import torch
import numpy as np

In [3]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

In [7]:
x_ones = torch.ones_like(x_data)
print(x_ones)

x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[1, 1],
        [1, 1]])
tensor([[0.3376, 0.9450],
        [0.7962, 0.5673]])


In [16]:
shape = (2,3,) # just a convention, it seems
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(rand_tensor, '\n', ones_tensor, '\n',zeros_tensor)

tensor([[0.5746, 0.0029, 0.8660],
        [0.0119, 0.5040, 0.3543]]) 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [17]:
tensor = torch.rand(3,4)

print(f'shape: {tensor.shape}')
print(f'datatype: {tensor.dtype}')
print(f'device tensor is stored on: {tensor.device}')

shape: torch.Size([3, 4])
datatype: torch.float32
device tensor is stored on: cpu


In [19]:
if torch.cuda.is_available():
    tensor = tensor.to('cuda')
    print('GPU AVAILABLE')

In [21]:
tensor = torch.ones(4,4)
print(tensor[0])
print(tensor[...,-1])

tensor([1., 1., 1., 1.])
tensor([1., 1., 1., 1.])


In [34]:
t2 = torch.cat([tensor, tensor, tensor], dim=0)
t2, t2.shape

(tensor([[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]),
 torch.Size([12, 4]))

In [38]:
t1 = torch.stack([tensor, tensor, tensor], dim=1)
t1, t1.shape

(tensor([[[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]],
 
         [[1., 1., 1., 1.],
          [1., 1., 1., 1.],
          [1., 1., 1., 1.]]]),
 torch.Size([4, 3, 4]))

`.cat`: Concatenates the given sequnce of tensors **in the given dimension**

`.stack`: Concatenates sequence of tensors along a **new dimension**

In [42]:
# Matric Multiplication; y1, y2, y3 will have the same value
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(tensor)
print(y3)
torch.matmul(tensor, tensor.T, out=y3) # basically it just overwrites it

print(y1)
print(y2)
print(y3)

tensor([[0.4024, 0.7745, 0.1068, 0.0688],
        [0.1432, 0.9073, 0.5444, 0.1393],
        [0.0688, 0.8549, 0.3094, 0.4640],
        [0.1580, 0.8615, 0.3920, 0.8344]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])
tensor([[4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.],
        [4., 4., 4., 4.]])


In [44]:
# Element-wise product; z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [47]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

16.0 <class 'float'>


In [49]:
# In-place operations: stores the result into the operand.
print(tensor)
tensor.add_(5)
print(tensor)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])


### Bridge with Numpy

Tensors on the CPU and NumPy arrays can share their underlying memory locations, and changing one will change the other.

In [64]:
t = torch.ones(5)
n = t.numpy()

print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [66]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [68]:
n = np.ones(5)
t = torch.from_numpy(n)

In [69]:
np.add(n, 1, out=n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
